config/urls.py
from django.contrib import admin
from django.urls import include, path

from pybo.views import base_views

# 폴더안에 init__이있어야 인식을함
# /기본url 추가해줘ㅑ함 login redirect url추가했으면
# url패턴도추가해야하는것 패턴추가안하면 아무것도모름
urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/',include('pybo.urls')),    
    path('common/',include('common.urls')),
    path('',base_views.index,name='index'),
    # /할필요는 없다 ''=/기때문 /쓰면 //가됨
    # admin/도 /admin/이거라서  다른url도 /를 끝에다붙이는것
]

pybo/urls.py
from django.urls import path, re_path

from . import views
from .views import answer_view, base_views, question_view

app_name='pybo'
urlpatterns = [
    # base_views.py
    path('',base_views.index,name='index'),
    path('<int:question_id>/',base_views.detail,name='detail'),
    
    
    path('question/vote/<int:question_id>',question_view.question_vote,name='question_vote'),
    path('question/create/',question_view.question_create,name='question_create'),
    path('question/modify/<int:question_id>/', question_view.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',question_view.question_delete,name='question_delete'),
    
    path('answer/vote/<int:answer_id>',answer_view.answer_vote,name='answer_vote'),
    path('answer/create/<int:question_id>/',answer_view.answer_create,name='answer_create'),
    path('answer/modify/<int:answer_id>/',answer_view.answer_modify,name='answer_modify'),
    path('answer/delete/<int:answer_id>/',answer_view.answer_delete,name='answer_delete'),
#    forms.from 일반폼과 forms.Modelform은 다름
# 페이지요청시 전달되는 파라미터를 관리하기위한 클래스 
    # 끝에 /를붙여줘야 실행됨/2/이런식으로
    # url과 view조합이 controlleㄱ라고봐야함
]

pybo/models.py
from django.contrib.auth.models import User
from django.db import models


# 모델에 추가할때마다 MIGRATE하기
# Create your models here.
class Question(models.Model):
    # 다대다는 중간테이블을 사용해서 두모델간의 관계를 관리하므로 on_delete가 의미가없음
    # on_dleete는 foreieng이나 onetoonefiled에서만관리
    voter=models.ManyToManyField(User,related_name='voter_question')
    # 각각 다르게  question을 여러개 가질수있기때문에 voter 1개가 Quesiton다를 가진다는것
    # 한마디로 voter가 여러개의 값을 가진다는것이다 1=여러개값을 가지는거고 다가 1개임
    
    # 역참조를통해서이제 user.voter_question가능 저거정안정하면 자동으로 question_set이되는데
    # 이럴경우 voter랑 author 모두 question_set으로 해당하기떄문에 어떤 필드로부터 역참조할지 알수가없음
    # voter로부터의 역참조,author로부터의 역참조는 각각 다 다름 한마디로 voter에 
    # voter의 question와 author 의 qeustion 은 다를수있따
    # voter의 question 역참조값과 author의 question 역참조는 다를 수있음
    # 각각 다른 집합을 가지는거니까 주의 각각의 필드는 다른 값을 가질수있따 주의
    
    # 필드들은 일단 다 1 Question 다
    # realated name을 사용안할시 modelname_set 예시: question_set으로 사용함
    # 또는 동일한 두모델간에 여러관계가있으면 각 관계 구분가능
    # Question에는 author과 voter라는 두개의 User관계가있기때문에
    # Question:User=다:1인데 필드는 author과 voter두개가 되어있어서
    # 어느필드로부터 역참조를할지 모르니까 결정해줘야함
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='author_question')
    # 모델의 메서드 foreingeky,CASECADE on_dleete는 옵션 kwargs**
    modify_date=models.DateTimeField(null=True,blank=True)
    subject=models.CharField(max_length=200)
    content=models.TextField()
    create_date=models.DateTimeField()
    def __str__(self):
        return self.subject
class Answer(models.Model):
    voter=models.ManyToManyField(User,related_name='author_answer')
    # Answer이 다 question이 1
    author=models.ForeignKey(User,on_delete=models.CASCADE,null=True,related_name='voter_answer')
    modify_date=models.DateTimeField(null=True,blank=True)
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    content=models.TextField()
    create_date=models.DateTimeField()

pybo/views.py
from email import message

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

from pybo.form import AnswerForm, QuestionForm
from pybo.models import Answer, Question


# Create your views here.
def index(request):
    page=request.GET.get('page','1')
    # pybo/?page=1처럼 값을가져올때 사용
    # request.get할텐데 page=1로 사용하라
    # 없을경우 default로 1로 사용하라는뜻
    # request는 컨트롤러로부터 model을 담은 매개변수라고보면되나?
    question_list=Question.objects.order_by('-create_date')
    paginator=Paginator(question_list,10)
    # 10개까지자른것만 page_obj에서 기본으로 보여라
    # 전체틀은 10씩이고
    # 페이지당 보여줄 개수
    page_obj=paginator.get_page(page)
    question_list=page_obj
    question_list.has_previous
    question_list.has_next
    question_list.number
    question_list.paginator.page_range
    question_list.previous_page_number
    question_list.next_page_number
    question_list.paginator.count
    question_list.start_index
    
    # 이렇게 옵젝으로 설정안하고 속성안하면 html에서 다음으로 못넘어가기때문 
    # page1기본값을 page_obj에 넣음
    # page_obj= 10개중에 일단 get_page 초기값 1로 보여줌
    # 객체를 생성해서 데이터만 조회하도록 쿼리,즉 속성할당하기위해씀
    # 속성을 html에 적용하기위해 context에 전달
    context={'question_list':page_obj}
    
    
    # context={'question_list':question_list}
    return render(request,'pybo/question_list.html',context)

def detail(request,question_id):
    # 자료형만가져오는거고 실질적으로는 controlleㄱ에서 받아오는것
    question=get_object_or_404(Question,pk=question_id)
    question.content

    question.answer_set.count
    context={'question':question}
    return render(request,'pybo/question_detail.html',context)

# 로그인화면으로 들어가라 만일안될경우

@login_required(login_url='common:login')
def question_create(request):
    # 질문등록하기눌러서 get방식으로 화면렌더링하는게있고
    # post를눌러서 model을 등록하는게있음
    # 그러므로 구별해야함
    if request.method == "POST":
        form=QuestionForm(request.POST)

        print(request.POST)
        if form.is_valid():
            
            question=form.save(commit=False)
            question.author=request.user
            # request.user=anonymouseuser 아까 model에서 틀리게 적어서 자동으로
            # 그렇게세팅됨
            # 임시저장만하라 아직 저장은하지말라라는뜻 모델에 subject,content만있어서
            # datetime은없기때문 다하고 save를한다
            question.create_date=timezone.now()
            question.save()
            return redirect('pybo:index')
    else: 
        # request.method=='get'이라고보면됨
        form=QuestionForm()
    context={'form':form}
    return render(request,'pybo/question_form.html',context)
    
@login_required(login_url='common:login')
def question_modify(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    if request.user != question.author:
        messages.error(request,'수정권한이 없음')
        return redirect('pybo:detail',question_id=question.id)
    if request.method == "POST":
        form=QuestionForm(request.POST,instance=question)
        if form.is_valid():
            question=form.save(commit=False)
            question.modify_date=timezone.now()  
            question.save()
            return redirect('pybo:detail',question_id=question.id)
        
    else:
        form=QuestionForm(instance=question)
    context={'form':form}
    return render(request,'pybo/question_form.html',context)


@login_required(login_url='common:login')
def question_delete(request,question_id):
    quesiton=get_object_or_404(Question,pk=question_id)
    if request.user != quesiton.author:
        messages.error('삭제권한없음')
        return redirect('pybo:detail',quesiton.id)
    quesiton.delete()
    return redirect('pybo:index')

@login_required(login_url='common:login')
def answer_modify(request,answer_id):
    # url.py 로부터 answer_id를 기본키에 전달해야함 안그러면 unpack int라고 해서 못찾음
    answer=get_object_or_404(Answer,pk=answer_id)
    if request.user != answer.author:
        messages.error(request,'수정권한x')
        return redirect('pybo:detail',answer.question.id)
    
    if request.method == "POST":
        form=AnswerForm(request.POST,instance=answer)
        if form.is_valid():
            # answer이 answer_id를 가져온게아닌 POST데이터를 가져온 form으로 업뎃함
            answer=form.save(commit=False)
            answer.modify_date=timezone.now()
            answer.save()
        # 트랜잭션 읽,쓰,수를 한단위로 실행하며 하나라도 실패하는순간 되돌아감 and연산 중요
        # save()는 트랜잭션에서 필수요소 save()가 안되면 트랜잭션이 완성안되므로  에러가뜸
        return redirect('pybo:detail',answer.question.id)
    else:
        form=AnswerForm(instance=answer)
    context={'answer':answer,'form':form}
            # answer은 현재,과거를 하려는거고
            # form은 내가 막 입력하거나 수정하려할때 쓰는거라고봐야함
    return render(request,'pybo/answer_form.html',context)   
        # instance는 채워주기도하며 기존에있는 instaceㅇ레코드를 연결하는 걸 뜻함

@login_required(login_url='common:login')
def answer_create(request,question_id):
    
    question=get_object_or_404(Question,pk=question_id)
    # question.answer_set.create(content=request.POST.get('content'),create_date=timezone.now())
    if request.method == "POST":
        # post클릭시 form에 post를 넣는다. 반응을넣음
        form=AnswerForm(request.POST)
        if form.is_valid():
            
            answer=form.save(commit=False)
            answer.author=request.user
            
            answer.create_date=timezone.now()
            answer.question=question
            answer.save()
            return redirect('pybo:detail',question.id)
    else:
        form=AnswerForm()
    context={'question':question,'form':form}
    return render(request,'pybo/question_detail.html',context)

        # post는 render할필요없음 왜냐하면 안에서 model을 생성하기때문
        
    
        
    # request.POST는 넣은것 여기서 get(매개변수)해서 답변내용을 가져옴 textarea
    
# html상에서 post가들어있으면 굳이 post로부터 받아오는거기때문에 render로 context를 전달안해도되는것
# render해서 가져오는 값이없으므로 redirect로 다른곳으로 가고됨

@login_required(login_url='common:login')
def answer_delete(request,answer_id):
    # url.py 변수랑 일치해야함 위의 argument가
    # 또한 form은 입력필드를 자동제공해주며, 필드와 오류메세지등을 렌더링하는데도
    # 주요사용됨 입력일단 시킬려면 model form을 써야함 
    answer=get_object_or_404(Answer,pk=answer_id)
    if request.user != answer.author:
        messages.error(request,'삭제권한x')
    else:
        answer.delete()
    return redirect('pybo:detail',question_id=answer.question.id)
 # request:httprequest형식
# request.POST는 눌렀을때 반영되는 데이터를 뜻함
# request는 뭘하기직전의 상태를 뜻한다고봐도됨
# 빈껍대기를 html에 

pybo/views/answer_view.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render, resolve_url
from django.utils import timezone

from ..form import AnswerForm
from ..models import Answer, Question


@login_required(login_url='common:login')
def answer_vote(request,answer_id):
    answer=get_object_or_404(Answer,pk=answer_id)
    if request.user == answer.author:
        messages.error(request,'본인 추천 x')
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(
            resolve_url('pybo:detail',answer.question.id),answer.id))
# answer.id 하면 주소가달라서 detail question이아닌 다른쪽으로 넘어갈것임
    

@login_required(login_url='common:login')
def answer_modify(request,answer_id):
    # url.py 로부터 answer_id를 기본키에 전달해야함 안그러면 unpack int라고 해서 못찾음
    answer=get_object_or_404(Answer,pk=answer_id)
    if request.user != answer.author:
        messages.error(request,'수정권한x')
        return redirect('pybo:detail',answer.question.id)
    
    if request.method == "POST":
        form=AnswerForm(request.POST,instance=answer)
        if form.is_valid():
            # answer이 answer_id를 가져온게아닌 POST데이터를 가져온 form으로 업뎃함
            answer=form.save(commit=False)
            answer.modify_date=timezone.now()
            answer.save()
        # 트랜잭션 읽,쓰,수를 한단위로 실행하며 하나라도 실패하는순간 되돌아감 and연산 중요
        # save()는 트랜잭션에서 필수요소 save()가 안되면 트랜잭션이 완성안되므로  에러가뜸
        return redirect('{}#answer_{}'.format(
            resolve_url('pybo:detail',answer.question.id),answer.id))
    else:
        form=AnswerForm(instance=answer)
    context={'answer':answer,'form':form}
            # answer은 현재,과거를 하려는거고
            # form은 내가 막 입력하거나 수정하려할때 쓰는거라고봐야함
    return render(request,'pybo/answer_form.html',context)   
        # instance는 채워주기도하며 기존에있는 instaceㅇ레코드를 연결하는 걸 뜻함

@login_required(login_url='common:login')
def answer_create(request,question_id):
    
    question=get_object_or_404(Question,pk=question_id)
    # question.answer_set.create(content=request.POST.get('content'),create_date=timezone.now())
    if request.method == "POST":
        # post클릭시 form에 post를 넣는다. 반응을넣음
        form=AnswerForm(request.POST)
        if form.is_valid():
            
            answer=form.save(commit=False)
            answer.author=request.user
            
            answer.create_date=timezone.now()
            answer.question=question
            answer.save()
            redirect('{}#answer_{}'.format(
            resolve_url('pybo:detail',answer.question.id),answer.id))
    else:
        form=AnswerForm()
    context={'question':question,'form':form}
    return render(request,'pybo/question_detail.html',context)

        # post는 render할필요없음 왜냐하면 안에서 model을 생성하기때문
        
    
        
    # request.POST는 넣은것 여기서 get(매개변수)해서 답변내용을 가져옴 textarea
    
# html상에서 post가들어있으면 굳이 post로부터 받아오는거기때문에 render로 context를 전달안해도되는것
# render해서 가져오는 값이없으므로 redirect로 다른곳으로 가고됨

@login_required(login_url='common:login')
def answer_delete(request,answer_id):
    # url.py 변수랑 일치해야함 위의 argument가
    # 또한 form은 입력필드를 자동제공해주며, 필드와 오류메세지등을 렌더링하는데도
    # 주요사용됨 입력일단 시킬려면 model form을 써야함 
    answer=get_object_or_404(Answer,pk=answer_id)
    if request.user != answer.author:
        messages.error(request,'삭제권한x')
    else:
        answer.delete()
    return redirect('pybo:detail',question_id=answer.question.id)
 # request:httprequest형식
# request.POST는 눌렀을때 반영되는 데이터를 뜻함
# request는 뭘하기직전의 상태를 뜻한다고봐도됨
# 빈껍대기를 html에 

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404, render

from ..models import Question


# Create your views here.
def index(request):
    page=request.GET.get('page','1')
    kw=request.GET.get('kw','')
    # 기본값 '' ,1
    # get('id',기본값) 으로 정함
    
    # pybo/?page=1처럼 값을가져올때 사용
    # request.get할텐데 page=1로 사용하라
    # 없을경우 default로 1로 사용하라는뜻
    # request는 컨트롤러로부터 model을 담은 매개변수라고보면되나?
    question_list=Question.objects.order_by('-create_date')
    
    if kw:
        question_list=question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(answer__content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()
        
        pass
    # d
    # git init 초기화부터하고, gitstatus하면 빈폴더만나옴
    #  git add *해야 파일까지다 넣는거고 gitstatus하면 주즈륵나옴
    # .idea나 db.sqlite는 사옹자,시스템별로 달라지기때문에 깃으로 관리하면 x
    # .idea = 파이참, db.sqlite=sqlite 데이터베이스 파일
    # 사용자 개인 데이터 는 다빼야함 오직템플릿만
    paginator=Paginator(question_list,10)
    page_obj=paginator.get_page(page)
    context={'question_list':page_obj,'page':page,'kw':kw}
    return render(request,'pybo/question_list.html',context)
    # 10개까지자른것만 page_obj에서 기본으로 보여라
    # 전체틀은 10씩이고
    # 페이지당 보여줄 개수
    # 객체만 render하는거고 객체를 html에서 메소드를통해구현하는것

    
    # 이렇게 옵젝으로 설정안하고 속성안하면 html에서 다음으로 못넘어가기때문 
    # page1기본값을 page_obj에 넣음
    # page_obj= 10개중에 일단 get_page 초기값 1로 보여줌
    # 객체를 생성해서 데이터만 조회하도록 쿼리,즉 속성할당하기위해씀
    # 속성을 html에 적용하기위해 context에 전달
    
    
    
    # context={'question_list':question_list}
    

def detail(request,question_id):
    # 자료형만가져오는거고 실질적으로는 controlleㄱ에서 받아오는것
    question=get_object_or_404(Question,pk=question_id)
    question.content

    question.answer_set.count
    context={'question':question}
    return render(request,'pybo/question_detail.html',context)

templates/pybo/answer_form.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="content" class="form-label">답변내용</label>
                <textarea name="content" id="content" class="form-control" rows="10">{{form.content.value|default_if_none:''}}</textarea>
                {% comment %} answer을 form에전달해서 현재 내용을알수있음 form.content.value형식으로 {% endcomment %}
            </div>
            <button type="submit"  class="btn btn-primary">저장하기</button>
        </form>
</div>



{% endblock  %}

templates/pybo/question_detail.html
{% extends "base.html" %}
{% load pybo_filter %}
{% block content %}
{% comment %} card는 이미지 텍스트 버튼 링크등 다 활용가능 img h5 p a 등다 가능 {% endcomment %}
<div class="container my-3">
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{message.tags}} </strong>
        <ul><li>{{message.message}} </li></ul>
        {% comment %} ul은 unorder list ,li=list item {% endcomment %}
    {% endfor %}
</div>
    {% endif %}
    {% comment %} setting에서 template에 message가 포함됨 {% endcomment %}
    <h2 border-bottom py-2>{{question.subject}} </h2>
        <div class="card my-3">
            <div class="card-body">
                {% comment %} card-body 컨텐츠 포함부분 {% endcomment %}
                <div class="card-text">{{question.content|mark}}</div>
                {% comment %} d-flex display속성설정요소->flexvbox로 justify-content-end 오른쪽으로 정렬 {% endcomment %}
                <div class="d-flex justify-content-end">
                    

                    {% if question.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ question.modify_date }}</div>
                    </div>
                    {% endif %}

                    <div class="badge bg-light text-dark p-2 text-start">
                        <div class="mb-2">{{question.author.username}} </div>
                        <div>{{ question.create_date}}</div>
                    </div>
                </div>
                <div class="my-3">
                    <a href="javascript:void(0)" data-uri="{% url 'pybo:question_vote' question.id %}"
                    class="recommend btn btn-sm btn-outline-secondary"
                     >추천
                    <span class="badge rounded-pill bg-success" >{{question.voter.count}} </span>
                    </a>
                    {% if request.user == question.author %}
                    {% comment %} url은 딕셔너리형태로 쓰는거고 name으로 찾는거기때문에
                    무조건 딕셔너리형태로 url을 받아와야함 {% endcomment %}

                        <a href="{% url 'pybo:question_modify' question.id %}"
                        class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                        data-uri="{% url 'pybo:question_delete' question.id %}"
                        {% comment %} data중 url를 넣음 {% endcomment %}
                        >삭제</a>
                    {% endif %}
                    
                </div>
            </div>
        </div>
        {% comment %} 모델.역참조하려면 context.model의 소문자형_set {% endcomment %}
        <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변 </h5>
        {% for answer in  question.answer_set.all %} 
        <a id="answer_{{answer.id}} "></a>
        {% comment %} <a id>는 앵커테그를위한 것 answer.id=18이면 id=answer_17임 {% endcomment %}
        {% comment %} 역참조메서드 all,count,filter(모든객체),get(1개),exclude(관계객체제외)
        order_by,annoate추가정보추가 values() 특정값 필드('id,answertext'),update 
        Question.objects의 메서드와 같다{% endcomment %}
        <div class="card my-3">
                <div class="card-body">
                    <div class="card-text">{{ answer.content|mark }}</div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date  %}
                        
                        <div class="badge bg-light text-dark p-2 text-start">
                            <div class="mb-2">{{question.author.username}} </div>
                            <div>{{answer.modify_date }}</div>
                        </div>
                        {% endif %}

                        <div class="badge bg-light text-dark p-2 text-start">
                            <div class="mb-2">{{question.author.username}} </div>
                            <div>{{answer.create_date }}</div>
                        </div>
                    </div>
                    <div class="my-3">
                        <a href="javascript:void(0)" data-uri="{% url 'pybo:answer_vote' answer.id %}"
                        class="recommend btn btn-sm btn-outline-secondary"
                        >추천
                        <span class="badge rounded-pill bg-success">{{answer.voter.count}} </span>
                    </a>
                        {% if request.user == answer.author %}
                        <a href="{% url 'pybo:answer_modify' answer.id %}"
                        class="btn btn-sm btn-outline-secondary"
                        >수정</a>
                        <a href="#"
                        class="delete btn btn-sm btn-outline-secondary"
                        data-uri="{% url 'pybo:answer_delete' answer.id %}"
                        >삭제</a>

                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}     
            <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
                {% if  form.errors %}
                <div class= "alert alert-danger" role="alert">
                        {% for field in  form %}
                        {% if field.errors %}
                        {% comment %} error가났다는건 model이 null이있다는것 {% endcomment %}
                        <div>
                            <strong>{{field.label}} </strong>
                            {{field.errors}}
                        </div>
                        {% endif %}
                        {% endfor %}

                </div>
                {% endif %}
                {% csrf_token %}
                <div class="mb-3">
                    <label for="content" class="form-label">답변내용</label>

                {% comment %} 답변내용클릭시 textare로 포커스 이동 {% endcomment %}
                    <textarea {% if not user.is_authenticated  %}disabled{% endif %}
                    name="content" id="content" class="form-control" rows="10"></textarea>
                    {% comment %} id는 css name은 view에 전달 {% endcomment %}
                    {% comment %} form-label이나 form-control은 모델 불러오는것과 관련없고 그냥 부트스트랩임 {% endcomment %}
                    <input type="submit" value="답변등록" class="btn btn-primary">
                </div>
                </form>
</div>  

{% endblock  %}

{% block script %}
<script type="text/javascript">
const delete_elements=document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element){
    element.addEventListener('click',function(){
        if(confirm('정말삭제?')){
         location.href=this.dataset.uri;   
         
        }
        

    });

});
const recommend_eleemnts=document.getElementsByClassName('recommend');
Array.from(recommend_eleemnts).forEach(function(element){
    element.addEventListener('click',function(){
        if(confirm("정말추천?")){
            location.href=this.dataset.uri;
            
        }
    });

});
{% comment %} this.dataset  가져오라는뜻 폼에서 {% endcomment %}
{% comment %} 팝업창만나와도됨 아직 url에 연결안시켰으므로 {% endcomment %}
{% comment %} 일단먼저 class찾고 array.from에서 찾은걸 순환한다음 classname찾은거의 속성을 다 찾기위해 
foreach를 씀 function(element를함) {% endcomment %}
{% comment %} dataset(data-url)중의 url을 호출하라  {% endcomment %}

{% comment %} if는 대신 세미콜론 {% endcomment %}
{% comment %} (){}는 블록이들어가기때문에 ;로안묶음 {% endcomment %}
{% comment %} foreach 메서드 ; % endcomment %}
{% comment %} 블록의 시작과 끝은 세콜론x 문장끝 세미콜론 ㅇ ()괄호가 끝임 {% endcomment %}
</script>

{% endblock  %}
{% comment %} url넣고 매개변수는 그옆에 넣는다 {% endcomment %}

{% comment %} csrf 토큰을 세션통해서 발행후 폼+토큰을 전달, 그럼 웹페이지에서 토큰 하는 과정 {% endcomment %}

templates/pybo/question_form.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
        <form method="post" >
            {% comment %} action을주면 그 url view만가능하고 다른건 불가능하기때문에
            수정하려면 action빼는게나음 {% endcomment %}
            {% csrf_token %}
            {% if form.errors %}
            <div class= "alert alert-danger" role="alert">

                {% comment %} form의 요소들을 field로 정의
                field는 errors와 label 다 가질수있음  {% endcomment %}
                {% for field  in  form %}
                {% if field.errors %}
                    <strong>{{field.label}} </strong>
                    {{field.errors}}
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            
            <div class="mb-3">
                <label for="subject" class="form-label">제목</label>
                <input type="text" class="form-control" name="subject" id="subject"
                value="{{form.subject.value|default_if_none:""}}">
            </div>
            <div class="mb-3">
                <label for="content" class="form-label">내용</label>
                <textarea class="form-control" name="content" id="content" rows="10"
                >{{form.content.value|default_if_none:''}}</textarea>
            </div>
            {% comment %} subject,content charfield textfield타입자동설정 {% endcomment %}
            {% comment %} form태그에 action을안넣어줌
            보통은 action속성지정후 submit 실행시 url로 폼을전송해야하는게맞음
            하지만 현재에서는 action을 지정안해서 디폴트 액션으로 지정함
            action="{% url 'pybo:question_create' %}" 로해도됨             {% endcomment %}
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
</div>

{% endblock  %}