common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path

from . import views

app_name = 'common'

urlpatterns = [
    # AuthenticationForm을 기본뷰로 사용자동생성 loginview는 그럼
    # 자동으로 template_name에 form context르르 추가해줌
    
    path('login/',auth_views.LoginView.as_view(template_name='common/login.html'),name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('signup/',views.singup,name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from pybo.views import base_views

# 폴더안에 init__이있어야 인식을함
# /기본url 추가해줘ㅑ함 login redirect url추가했으면
# url패턴도추가해야하는것 패턴추가안하면 아무것도모름
urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/',include('pybo.urls')),    
    path('common/',include('common.urls')),
    path('',base_views.index,name='index'),
    # /할필요는 없다 ''=/기때문 /쓰면 //가됨
    # admin/도 /admin/이거라서  다른url도 /를 끝에다붙이는것
]

pybo/urls.py
from django.urls import path, re_path

from . import views
from .views import answer_view, base_views, question_view

app_name='pybo'
urlpatterns = [
    # base_views.py
    path('',base_views.index,name='index'),
    path('<int:question_id>/',base_views.detail,name='detail'),
    
    
    path('question/vote/<int:question_id>',question_view.question_vote,name='question_vote'),
    path('question/create/',question_view.question_create,name='question_create'),
    path('question/modify/<int:question_id>/', question_view.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',question_view.question_delete,name='question_delete'),
    
    path('answer/vote/<int:answer_id>',answer_view.answer_vote,name='answer_vote'),
    path('answer/create/<int:question_id>/',answer_view.answer_create,name='answer_create'),
    path('answer/modify/<int:answer_id>/',answer_view.answer_modify,name='answer_modify'),
    path('answer/delete/<int:answer_id>/',answer_view.answer_delete,name='answer_delete'),
#    forms.from 일반폼과 forms.Modelform은 다름
# 페이지요청시 전달되는 파라미터를 관리하기위한 클래스 
    # 끝에 /를붙여줘야 실행됨/2/이런식으로
    # url과 view조합이 controlleㄱ라고봐야함
]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404, render

from ..models import Question


# Create your views here.
def index(request):
    page=request.GET.get('page','1')
    kw=request.GET.get('kw','')
    # 기본값 '' ,1
    # get('id',기본값) 으로 정함
    
    # pybo/?page=1처럼 값을가져올때 사용
    # request.get할텐데 page=1로 사용하라
    # 없을경우 default로 1로 사용하라는뜻
    # request는 컨트롤러로부터 model을 담은 매개변수라고보면되나?
    question_list=Question.objects.order_by('-create_date')
    
    if kw:
        question_list=question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(answer__content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()
        
        pass
    # d
    # git init 초기화부터하고, gitstatus하면 빈폴더만나옴
    #  git add *해야 파일까지다 넣는거고 gitstatus하면 주즈륵나옴
    # .idea나 db.sqlite는 사옹자,시스템별로 달라지기때문에 깃으로 관리하면 x
    # .idea = 파이참, db.sqlite=sqlite 데이터베이스 파일
    # 사용자 개인 데이터 는 다빼야함 오직템플릿만
    paginator=Paginator(question_list,10)
    page_obj=paginator.get_page(page)
    context={'question_list':page_obj,'page':page,'kw':kw}
    return render(request,'pybo/question_list.html',context)
    # 10개까지자른것만 page_obj에서 기본으로 보여라
    # 전체틀은 10씩이고
    # 페이지당 보여줄 개수
    # 객체만 render하는거고 객체를 html에서 메소드를통해구현하는것

    
    # 이렇게 옵젝으로 설정안하고 속성안하면 html에서 다음으로 못넘어가기때문 
    # page1기본값을 page_obj에 넣음
    # page_obj= 10개중에 일단 get_page 초기값 1로 보여줌
    # 객체를 생성해서 데이터만 조회하도록 쿼리,즉 속성할당하기위해씀
    # 속성을 html에 적용하기위해 context에 전달
    
    
    
    # context={'question_list':question_list}
    

def detail(request,question_id):
    # 자료형만가져오는거고 실질적으로는 controlleㄱ에서 받아오는것
    question=get_object_or_404(Question,pk=question_id)
    question.content

    question.answer_set.count
    context={'question':question}
    return render(request,'pybo/question_detail.html',context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">


    <title>파이보변경</title>
</head>
<body>
    {% comment %} 기본템플릿시작 {% endcomment %}

{% include "navbar.html" %}
{% block content %}
{% endblock %}
<script src={% static 'bootstrap.min.js' %}></script>

{% block script %}

{% endblock  %}
{% comment %} 기본템플릿끝 {% endcomment %}
</body>
</html>

templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger" >
    {% for field in  form %}
    {% if field.errors %}
    <div>
        <strong>{{field.label}} </strong>
        {{field.errors}}
    </div>

    {% endif %}

    {% endfor %}
    {% for error  in  form.non_field_errors %}
    <div>
        <strong>{{error}} </strong>
    </div>
    {% endfor %}
</div>

{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %} ">Pybo</a>
        <button class="navbar-toggler" type="button" 
        data-bs-toggle="collapse" 
        {% comment %} bs들어가면 부트스트랩5 자바스크립트 속성뜻함 {% endcomment %}
        data-bs-target="#collapsibleNavId" 
        aria-controls="collapsibleNavId"
            aria-expanded="false" 
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                {% comment %} 인증이되었따면 django.contrib.auth기능을 사용해서 
                폼 User객체의 user를 쓰는게가능 {% endcomment %}
                {% if  user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:logout' %}">{{user.username}} (로그아웃) </a>
                </li>

                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                </li>
                <li class="nav-item">
                    {% if not user.is_authenticated %}
                    {% comment %} get용 {% endcomment %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>